title: Mehdi CHOU.
description: My Github Pages
author: mc.
logo: /static/img/avatar.png
github: https://github.com/codeasashu
about: posts & projects

baseurl: "https://mc-source.github.io"
url: "https://mc-source.github.io"

allowsearch: true

# disqus_shortname: aboutashu
# google_analytics: UA-72862926-1

# share:
#   twitter_username: \#
#   fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown

gems: [jekyll-paginate, jekyll-gist]
